Awaards/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'', include('awaardsapp.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^logout/$', views.logout, {"next_page": '/'}),
    url(r'^api-token-auth/', obtain_auth_token),
]

awaardsapp/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [ 

    url(r'^$', views.home_projects, name='homePage'),
    # url(r'^search/', views.search_users, name='search_users'),
    url(r'^search/', views.search_projects, name='search_projects'),
    url(r'^image(\d+)', views.project, name='project'),
    url(r'^users/', views.user_list, name='user_list'),
    url(r'^new/image$', views.new_image, name='new_image'),
    url(r'^new/project$', views.new_project, name='new_project'),
    url(r'^edit/profile$', views.edit_profile, name='edit_profile'),
    url(r'^profile/(?P<username>[0-9]+)$',
        views.individual_profile_page, name='individual_profile_page'),
    url(r'^ajax/newsletter/$', views.newsletter, name='newsletter'),
    url(r'^api/project/$', views.ProjectList.as_view()),
    url(r'api/project/project-id/(?P<pk>[0-9]+)/$',
        views.ProjectDescription.as_view()),
    url(r'^api/profile/$', views.ProfileList.as_view()),
    url(r'api/profile/profile-id/(?P<pk>[0-9]+)/$',
        views.ProfileDescription.as_view()),
    # ex: /
    url(r'^$', views.review_list, name='review_list'),
    # ex: /review/5/
    url(r'^review/(?P<review_id>[0-9]+)/$',
        views.review_detail, name='review_detail'),
    # ex: /project/
    url(r'^project$', views.project_list, name='project_list'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

awaardsapp/models.py
#from __future__ import unicode_literals
import numpy as np
from django.db.models.signals import post_save
from django.db.models import Avg, Max, Min

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
import datetime as dt

class tags(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    def save_tags(self):
        self.save()

    def delete_tags(self):
        self.delete()

class Location(models.Model):
    name = models.CharField(max_length=30)


    def save_location(self):
        self.save()

    def delete_location(self):
        self.delete()

    def __str__(self):
        return self.name


class Project(models.Model):
    title = models.TextField(max_length=200, null=True, blank=True, default="title")
    project_image = models.ImageField(upload_to='picture/', null=True, blank=True)
    description = models.TextField()
    project_url=models.URLField(max_length=250)

    def average_design(self):
        design_ratings = list(map(lambda x: x.design_rating, self.reviews.all()))
        return np.mean(design_ratings)

    def average_usability(self):
        usability_ratings = list(map(lambda x: x.usability_rating, self.reviews.all()))
        return np.mean(usability_ratings)

    def average_content(self):
        content_ratings = list(map(lambda x: x.content_rating, self.reviews.all()))
        return np.mean(content_ratings)

    def save_project(self):
        self.save()

    @classmethod
    def delete_project_by_id(cls, id):
        projects = cls.objects.filter(pk=id)
        projects.delete()

    @classmethod
    def get_project_by_id(cls, id):
        projects = cls.objects.get(pk=id)
        return projects

    @classmethod
    def search_projects(cls, search_term):
        projects = cls.objects.filter(title__icontains=search_term)
        return projects

    @classmethod
    def update_project(cls, id):
        projects = cls.objects.filter(id=id).update(id=id)
        return projects

    @classmethod
    def update_description(cls, id):
        projects = cls.objects.filter(id=id).update(id=id)
        return projects

    def __str__(self):
        return self.title



class Profile(models.Model):
    class Meta:
        db_table = 'profile'

    bio = models.TextField(max_length=200, null=True, blank=True, default="bio")
    profile_pic = models.ImageField(upload_to='picture/', null=True, blank=True, default= 0)
    user=models.OneToOneField(User, on_delete=models.CASCADE, null=True, related_name="profile")
    project=models.ForeignKey(Project, null=True)
    contact=models.IntegerField(default=0)

    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    post_save.connect(create_user_profile, sender=User)


    def save_profile(self):
        self.save()

    def delete_profile(self):
        self.delete()


    @classmethod
    def search_users(cls, search_term):
        profiles = cls.objects.filter(user__username__icontains=search_term)
        return profiles

    @property
    def image_url(self):
        if self.profile_pic and hasattr(self.profile_pic, 'url'):
            return self.profile_pic.url

    def __str__(self):
        return self.user.username


class Image(models.Model):
    image=models.ImageField(upload_to='picture/', )
    name = models.CharField(max_length=40)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, related_name="images")
    description=models.TextField()
    location=models.ForeignKey(Location, null=True)
    tags=models.ManyToManyField(tags, blank=True)
    likes = models.IntegerField(default=0)
    comments= models.TextField(blank=True)

    def __str__(self):
        return self.name

    def save_image(self):
        self.save()

    @classmethod
    def delete_image_by_id(cls, id):
        pictures = cls.objects.filter(pk=id)
        pictures.delete()

    @classmethod
    def get_image_by_id(cls, id):
        pictures = cls.objects.get(pk=id)
        return pictures

    @classmethod
    def filter_by_tag(cls, tags):
        pictures = cls.objects.filter(tags=tags)
        return pictures

    @classmethod
    def filter_by_location(cls, location):
        pictures = cls.objects.filter(location=location)
        return pictures

    @classmethod
    def search_image(cls, search_term):
        pictures = cls.objects.filter(name__icontains=search_term)
        return pictures

    @classmethod
    def update_image(cls, id):
        pictures=cls.objects.filter(id=id).update(id=id)
        return pictures

    @classmethod
    def update_description(cls, id):
        pictures = cls.objects.filter(id=id).update(id=id)
        return pictures


class Review(models.Model):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
        (9, '9'),
        (10, '10'),

    )
    project = models.ForeignKey(Project, null=True, blank=True, on_delete=models.CASCADE, related_name="reviews")
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE, related_name='reviews')
    image = models.ForeignKey(Image, on_delete=models.CASCADE, related_name="reviews", null=True, blank=True)
    comment = models.TextField()
    design_rating = models.IntegerField(choices=RATING_CHOICES, default=0)
    usability_rating = models.IntegerField(choices=RATING_CHOICES, default=0)
    content_rating = models.IntegerField(choices=RATING_CHOICES, default=0)

    def save_comment(self):
        self.save()

    def get_comment(self, id):
        comments = Review.objects.filter(image_id =id)
        return comments

    def __str__(self):
        return self.comment

class NewsLetterRecipients(models.Model):
    name = models.CharField(max_length = 30)
    email = models.EmailField()

class Like(models.Model):
    user = models.ForeignKey(User)
    image = models.ForeignKey(Image)
    value = models.IntegerField(default=True, null=True, blank=True)

    def save_like(self):
        self.save()

    def __str__(self):
        return str(self.user) + ':' + str(self.image) + ':' + str(self.value)

    class Meta:
        unique_together = ("user", "image", "value")

awaardsapp/forms.py
from .models import Image, Review, Profile, Project
from django import forms
from django.forms import ModelForm, Textarea, IntegerField


class NewImageForm(forms.ModelForm):
    class Meta:
        model = Image
        exclude = ['user',]


class NewProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        exclude = ['user',]


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = [ 'usability_rating', 'design_rating', 'content_rating' , 'comment']
        widgets = {
            'comment': Textarea(attrs={'cols': 40, 'rows': 15}),
        }
class UpdatebioForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user',]


class NewsLetterForm(forms.Form):
    your_name = forms.CharField(label='First Name',max_length=30)
    email = forms.EmailField(label='Email')

awaardsapp/templates/base.html
{% load bootstrap3 %} {% load static%}

<html>

<head>
  <meta charset="utf-8"> {% if title %}
  <title> Image Gallery - {{title}}</title>
  {% else %}
  <title> The Image Gallery </title>
  {% endif %} {% block styles %} {% bootstrap_css %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Grand+Hotel" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Concert+One|Didact+Gothic|Dosis|K2D|Vidaloka" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
  {% endblock %}


</head>

<body>
  {% include "navbar.html" %} {% block content %}
  <h1 class='text-center'> Images for Today </h1> {%endblock%} {% block scripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

  {% bootstrap_javascript %} {% endblock %}



</body>

</html>

awaardsapp/templates/image.html
{% extends 'base.html' %} {% load static %} {% load bootstrap3%} {% block content %}
<link href="https://fonts.googleapis.com/css?family=Charmonman|Dancing+Script|Kodchasan|Spirax|Abril+Fatface" rel="stylesheet">

<div class="container">

  <div class="jumbotron text-center" style="background-color:white;">

    <h1 class="h1" style="font-family: 'Dosis', cursive; color:blue;font-size:70px;">Awards</h1>


  </div>
</div>

<div class="container">
<div class="card mb-3" style="width:40rem;;">
  <img class="card-img-top" src="{{project.project_image.url}}" alt="Card image cap" class="img-fluid" size="100px200">
  <div class="card-body">



    <h5 class="card-title" style="font-family: 'Dosis', sans-serif;"><strong>Project Name:</strong>
      <br>
      {{project.title}}</h5>
    <p class="card-text" style="font-family: 'Dosis', sans-serif;"><strong>Description Of Project:</strong>
      <br>
      {{project.description}}</p>
  </div>

  <div class="card border-secondary">
     <div class="card-header">
     <h5 style="font-family: 'Dosis', sans-serif;"> Comments</h5>
       </div>


     <div class="card-body text-primary">
<h4>
        {{ review.project.title }}
        </h4>
    {% for review in latest_review_list %}
    <div>

        <p style="color:black; font-family: 'Dosis',sans-serif;">Comment by {{ review.user }}: {{ review.comment }}</p>
    </div>


    {% endfor %}

          <h1 style="color:black;font-family: 'Dosis', sans-serif;">AVERAGE OF REVIEWS</h1>


<h5 style="font-family: 'Dosis',sans-serif;">{{ project.reviews.count }} reviews ({{ project.average_design | floatformat }} average rating of design)</h5>
<h5 style="font-family: 'Dosis',sans-serif;">{{ project.reviews.count }} reviews ({{ project.average_content | floatformat }} average rating of content)</h5>
<h5 style="font-family: 'Dosis',sans-serif;">{{ project.reviews.count }} reviews ({{ project.average_usability | floatformat }} average rating of usability)</h5>

<h3 style="font-family: 'Dosis', sans-serif;">Add your comment</h3>
  <hr>
  <form action=""  method="post" style="font-family: 'Dosis',sans-serif;">
    {%csrf_token%} {% bootstrap_form form %}
      <input type="submit" class="btn btn-primary" value="Post">
  </form>
  <hr>

</div>




     </div>
   </div>
</div>
</div>


<div class="container">
    <div class="col-md-12">
      <div class="footer text-center">
        <ul id="footer1">
          <li>ABOUT US</li>
          <li>SUPPORT</li>
          <li>PRESS</li>
          <li>API</li>
          <li>JOBS</li>
          <li>PRIVACY</li>
          <li>TERMS</li>
          <li>DIRECTORY</li>
          <li>PROFILES</li>
          <li>HASHTAGS</li>
          <li>LANGUAGE</li>
          <br>

          <li style="font-size:10px;"> <strong>© 2021 BRAMUEL AMARIATI</strong></li>
        </ul>

      </div>

    </div>
  </div>
{% endblock %}

awaardsapp/templates/index.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load static %}
{% block content %}
<link href="https://fonts.googleapis.com/css?family=Charmonman|Dancing+Script|Kodchasan|Spirax|Abril+Fatface" rel="stylesheet">

<div class="container">

  <div class="jumbotron text-center mb-0" id="jumbo" style="background-color:white;">

    <h1 class="h1" style="font-family: 'Dosis', cursive; color:blue;font-size:70px;">Awards</h1>
    <p class="h1" style="font-family: 'Dosis', cursive; color:black;font-size:25px;">View projects, submit your own projects and have them reviewed.</p>
  </div>
</div>


<div class="jumbotron itson mb-3 ">

  <div class="card-deck flex-wrap">
    {% for project in projects %}
    <div class="card border-secondary w-33"><a href="{% url 'project' project.id %}">

        <img src="{{project.project_image.url}}" data-target="#imageModal{{project.id}}" data-toggle="modal" alt="" class="img-fluid"
          id="eachimage1" size="100px200"></a>
      <p style="font-family: 'Dosis', sans-serif; text-align:center;"> {{ project.description}}</p>
     <p style="font-family: 'Dosis', sans-serif; text-align:center;"> {{ project.user.username}}</p>
     <span class="badge badge-pill badge-info" style="font-family: 'Dosis', sans-serif;">
       <a href="{{ project.project_url}}">Visit Site</a></span>
      <span class="badge badge-pill badge-danger" style="font-family: 'Dosis', sans-serif; text-align:center;">Like</span>
  <span class="badge badge-pill badge-warning" style="font-family: 'Dosis', sans-serif; text-align:center;"><a href="{% url 'project' project.id %}">View Project</a></span>

    </div>
    {% endfor %}
  </div>


</div>

<div class="jumbotron text-center mt-3" style="background-color:white;font-family: 'Dosis', sans-serif;">

  <form action="{%url 'homePage'%}" method="post">
    {%csrf_token%} {% bootstrap_form letterForm %}
    <input type="submit" style="background-color:white;" value="Subscribe To Awards ">
  </form>

</div>


<div class="container">
  <div class="col-md-12">
    <div class="footer text-center">
      <ul id="footer1">
        <li>ABOUT US</li>
        <li>SUPPORT</li>
        <li>PRESS</li>
        <li>API</li>
        <li>JOBS</li>
        <li>PRIVACY</li>
        <li>TERMS</li>
        <li>DIRECTORY</li>
        <li>PROFILES</li>
        <li>HASHTAGS</li>
        <li>LANGUAGE</li>
        <br>

        <li style="font-size:10px;"> <strong>© 2021 BRAMUEL AMARIATI</strong></li>
      </ul>
    </div>
  </div>
</div>

{% endblock %} {% block scripts %} {{block.super}}
<script type="text/javascript" src="{%static 'js/scripts.js'%}"></script>

{% endblock %}

awaardsapp/templates/project_details.html
{% extends 'base.html' %}

{% load bootstrap3 %}{% block content %}


<h2>{{ project.title }}</h2>
<h5>{{ project.review_set.count }} reviews ({{ project.design_rating | floatformat }} average rating of design)</h5>
<h5>{{ project.review_set.count }} reviews ({{ project.content_rating | floatformat }} average rating of content)</h5>
<h5>{{ project.review_set.count }} reviews ({{ project.usability_rating | floatformat }} average rating of usability)</h5>

{% block content %}
<h3>Recent reviews</h3>

{% if project.review_set.all %}
<div class="row">
    {% for review in project.review_set.all %}

    <div class="col-xs-6 col-lg-4">
        <em>{{ review.comment }}</em>
        <h6>Design Rated {{ review.design_rating}} of 10 by {{ review.user }}</h6>
        <h6>Content Rated {{ review.content_rating }} of 10 by {{ review.user }}</h6>
        <h6>Usability Rated {{ review.usability_rating }} of 10 by {{ review.user }}</h6>

    </div>
    {% endfor %}


</div>


{% endblock %}

awaardsapp/templates/review_detail.html
{% extends 'base.html' %}

{% block title %}
<h2><a href="{% url 'project_detail' review.project.id %}">{{ review.project.user }}</a></h2>
{% endblock %}

{% block content %}

<h4>Rated {{ review.content_rating }} of 10 by
    <a href="{% url 'individual_profile_page' review.user_name %}" >{{ review.user }}</a></h4>


<h4>Rated {{ review.design_rating }} of 10 by
    <a href="{% url 'individual_profile_page' review.user_name %}" >{{ review.user }}</a></h4>

<h4>Rated {{ review.usability_rating }} of 10 by
    <a href="{% url 'individual_profile_page' review.user_name %}" >{{ review.user }}</a></h4>
<p>{{ review.comment }}</p>
{% endblock %}

awaardsapp/templates/review_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}{% block content %}
<h2>Latest reviews</h2>

{% if latest_review_list %}
<div>
    {% for review in latest_review_list %}
    <div>
        <h4><a href="{% url 'review_detail' review.id %}">
        {{ review.wine.name }}
        </a></h4>
        <h6> Design Rating is {{ review.design_rating }} of 5 by {{ review.user }}</h6>
        <h6> Usability Rating is {{ review.usability_rating }} of 5 by {{ review.user }}</h6>
        <h6> Content Rating is {{ review.content_rating }} of 5 by {{ review.user }}</h6>
        <p>{{ review.comment }}</p>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews are available.</p>
{% endif %}
{% endblock %}

awaardsapp/templates/search.html
{%extends 'base.html'%} {% block content %}
<div class="container">

  <div class="row">
    {% if profiles %}
    <h2 style="font-family: 'Kodchasan', sans-serif;color:white;"> Here are profiles of your search term: {{message}}</h2>
    {% else %}
    <h2 style="font-family: 'Kodchasan', sans-serif;color:white;"> It appears that there are 0 profiles for your search term
      {{message}}, please try again. </h2>
    {% endif %}

  </div>

  <h1 style="font-family: 'Dosis', sans-serif;"><strong> These are the projects found </strong></h1>

  {% for profile in profiles %}
  <p style="font-family: 'Dosis', sans-serif;"><a href="{% url 'individual_profile_page' profile.user.id %}"> {{profile.user.username}}</a></p>
  {% endfor %}


  <div class="row">

    {% if projects %}
    <div class="container">

      <div class="card-columns">

        {% for project in projects %}
        <div class="card border-secondary">
          <img src="{{project.project_image.url}}" data-target="#imageModal{{project.id}}" data-toggle="modal" alt="" class="img-fluid" id="eachimage"
            size="100px200">
        </div>
        {% endfor %}
      </div>
    </div>

    {% endif %}
  </div>
</div>



<div class="container">
    <div class="col-md-12">
      <div class="footer text-center">
        <ul id="footer1">
          <li>ABOUT US</li>
          <li>SUPPORT</li>
          <li>PRESS</li>
          <li>API</li>
          <li>JOBS</li>
          <li>PRIVACY</li>
          <li>TERMS</li>
          <li>DIRECTORY</li>
          <li>PROFILES</li>
          <li>HASHTAGS</li>
          <li>LANGUAGE</li>
          <br>

          <li style="font-size:10px;"> <strong>© 2021 BRAMUEL AMARIATI</strong></li>
        </ul>

      </div>

    </div>
  </div>
{% endblock %}

awaardsapp/templates/user_list.html
{% extends 'base.html' %} {% block title %}
{% load bootstrap3 %}{% block content %}
<h2>List Of Users</h2>
{% endblock %} {% block content %} {% if user_list %}
<div class="row">
    {% for user in user_list %}
    <div class="col-xs-6 col-lg-4">
        <h4><a href="{% url 'user_list' user.id %}">
                {{ user.username }}
            </a></h4>
        <h5>{{ user.email }} </h5>


    </div>
    {% endfor %}
</div>
{% else %}
<p>No users are available.</p>
{% endif %} {% endblock %}
{% endblock %}